---
version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  file-lines:
    enabled: false
  return-statements:
    config:
      threshold: 10
plugins:
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
